const dummy = [
  {
    category: "Follow for updates",
    data: [
      "Twitter @xlongclaw"
    ],
  },
  {
    category: "Getting Started",
    data: [
      "Overview","Usage","Learn","FAQs"
    ],
  },
  {
    category: "Installation",
    data: [
      "Install Next.js",
      "Install Tailwind CSS",
      "Add utilities",
    ],
  },
  {
    category: "All Components",
    data: [
      "Otp Field",
      "Card Stack",
      "Background Gradient",
      "Image Slider",
      "Hero Paralax",
      "Lamp effect",
      "Layout Grid",
      "Moving Borders",
      "Hero Paralax",
      "Card Stack",
      "Image Slider",
      "Moving Borders",
      "Otp Field",
      "Lamp effect",
      "Background Gradient",
      "Layout Grid",
    ],
  },
  {
    category: "All Components",
    data: [
      "Otp Field",
      "Card Stack",
      "Background Gradient",
      "Image Slider",
      "Hero Paralax",
      "Lamp effect",
      "Layout Grid",
      "Moving Borders",
      "Hero Paralax",
      "Card Stack",
      "Image Slider",
      "Moving Borders",
      "Otp Field",
      "Lamp effect",
      "Background Gradient",
      "Layout Grid",
    ],
  },
  {
    category: "All Components",
    data: [
      "Otp Field",
      "Card Stack",
      "Background Gradient",
      "Image Slider",
      "Hero Paralax",
      "Lamp effect",
      "Layout Grid",
      "Moving Borders",
      "Hero Paralax",
      "Card Stack",
      "Image Slider",
      "Moving Borders",
      "Otp Field",
      "Lamp effect",
      "Background Gradient",
      "Layout Grid",
    ],
  },
  {
    category: "All Components",
    data: [
      "Otp Field",
      "Card Stack",
      "Background Gradient",
      "Image Slider",
      "Hero Paralax",
      "Lamp effect",
      "Layout Grid",
      "Moving Borders",
      "Hero Paralax",
      "Card Stack",
      "Image Slider",
      "Moving Borders",
      "Otp Field",
      "Lamp effect",
      "Background Gradient",
      "Layout Grid",
    ],
  },
  {
    category: "All Components",
    data: [
      "Otp Field",
      "Card Stack",
      "Background Gradient",
      "Image Slider",
      "Hero Paralax",
      "Lamp effect",
      "Layout Grid",
      "Moving Borders",
      "Hero Paralax",
      "Card Stack",
      "Image Slider",
      "Moving Borders",
      "Otp Field",
      "Lamp effect",
      "Background Gradient",
      "Layout Grid",
    ],
  },
];

export default dummy;
